Map<int, String> weatherMap = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog and depositing rime fog",
  48: "Fog and depositing rime fog",
  51: "Drizzle: Light intensity",
  53: "Drizzle: Moderate intensity",
  55: "Drizzle: Dense intensity",
  56: "Freezing Drizzle: Light intensity",
  57: "Freezing Drizzle: Dense intensity",
  61: "Rain: Slight intensity",
  63: "Rain: Moderate intensity",
  65: "Rain: Heavy intensity",
  66: "Freezing Rain: Light intensity",
  67: "Freezing Rain: Heavy intensity",
  71: "Snow fall: Slight intensity",
  73: "Snow fall: Moderate intensity",
  75: "Snow fall: Heavy intensity",
  77: "Snow grains",
  80: "Rain showers: Slight intensity",
  81: "Rain showers: Moderate intensity",
  82: "Rain showers: Violent intensity",
  85: "Snow showers: Slight intensity",
  86: "Snow showers: Heavy intensity",
  95: "Thunderstorm: Slight or moderate",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
};

Map<int, String> weatherIcons = {
  0: "assets/images/clear_sky.svg",
  1: "assets/images/few_clouds_02.svg",
  2: "assets/images/scattered_clouds_03.svg",
  3: "assets/images/broken_clouds_04.svg",
  45: "assets/images/mist_50.svg",
  48: "assets/images/mist_50.svg",
  51: "assets/images/rain_10.svg",
  53: "assets/images/rain_10.svg",
  55: "assets/images/shower_rain_09.svg",
  56: "assets/images/shower_rain_09.svg",
  57: "assets/images/shower_rain_09.svg",
  61: "assets/images/shower_rain_09.svg",
  63: "assets/images/shower_rain_09.svg",
  65: "assets/images/rain_10.svg",
  66: "assets/images/snow_13.svg",
  67: "assets/images/snow_13.svg",
  71: "assets/images/snow_13.svg",
  73: "assets/images/snow_13.svg",
  75: "assets/images/snow_13.svg",
  77: "assets/images/snow_13.svg",
  80: "assets/images/shower_rain_09.svg",
  81: "assets/images/shower_rain_09.svg",
  82: "assets/images/shower_rain_09.svg",
  85: "assets/images/snow_13.svg",
  86: "assets/images/snow_13.svg",
  95: "assets/images/thunder_11.svg",
  96: "assets/images/thunder_11.svg",
  99: "assets/images/thunder_11.svg",
};
// Map<int, String> weatherIcons = {
//   0: "https://openweathermap.org/img/wn/01d.png",
//   1: "https://openweathermap.org/img/wn/02d.png",
//   2: "https://openweathermap.org/img/wn/03d.png",
//   3: "https://openweathermap.org/img/wn/04d.png",
//   45: "https://openweathermap.org/img/wn/50d.png",
//   48: "https://openweathermap.org/img/wn/50d.png",
//   51: "https://openweathermap.org/img/wn/10d.png",
//   53: "https://openweathermap.org/img/wn/10d.png",
//   55: "assets/images/shower_rain_09.svg",
//   56: "assets/images/shower_rain_09.svg",
//   57: "assets/images/shower_rain_09.svg",
//   61: "assets/images/shower_rain_09.svg",
//   63: "assets/images/shower_rain_09.svg",
//   65: "https://openweathermap.org/img/wn/10d.png",
//   66: "assets/images/snow_13.svg",
//   67: "assets/images/snow_13.svg",
//   71: "assets/images/snow_13.svg",
//   73: "assets/images/snow_13.svg",
//   75: "assets/images/snow_13.svg",
//   77: "assets/images/snow_13.svg",
//   80: "assets/images/shower_rain_09.svg",
//   81: "assets/images/shower_rain_09.svg",
//   82: "assets/images/shower_rain_09.svg",
//   85: "assets/images/snow_13.svg",
//   86: "assets/images/snow_13.svg",
//   95: "assets/images/thnuder_11.svg",
//   96: "assets/images/thnuder_11.svg",
//   99: "assets/images/thnuder_11.svg",
// };

class Weather {
  const Weather(
    this.city,
    this.condition,
    this.currTemp,
    this.maxTemp,
    this.minTemp,
    this.nextWeek,
    this.rain,
    this.sunrise,
    this.sunset,
    this.windSpd,
  );
  final String city;
  final String currTemp;
  final String maxTemp;
  final String minTemp;
  final String windSpd;
  final String sunrise;
  final String sunset;
  final String rain;
  final Map<String, int> nextWeek;
  final int condition;
}
